MODEL (
  name synthea.payers,
  kind SEED (
    path '$root/../../data/syntheaRaw/payers.csv'
  ),
  columns (
    Id TEXT,
    NAME TEXT,
    OWNERSHIP TEXT,
    ADDRESS TEXT,
    CITY TEXT,
    STATE_HEADQUARTERED TEXT,
    ZIP TEXT,
    PHONE TEXT,
    AMOUNT_COVERED DOUBLE,
    AMOUNT_UNCOVERED DOUBLE,
    REVENUE DOUBLE,
    COVERED_ENCOUNTERS INTEGER,
    UNCOVERED_ENCOUNTERS INTEGER,
    COVERED_MEDICATIONS INTEGER,
    UNCOVERED_MEDICATIONS INTEGER,
    COVERED_PROCEDURES INTEGER,
    UNCOVERED_PROCEDURES INTEGER,
    COVERED_IMMUNIZATIONS INTEGER,
    UNCOVERED_IMMUNIZATIONS INTEGER,
    UNIQUE_CUSTOMERS INTEGER,
    QOLS_AVG DOUBLE,
    MEMBER_MONTHS INTEGER
  )
)
