[project]
name = "dbt-synthea"
version = "0.1.0"
description = "dbt demo mirroring the SQLMesh Synthea tutorial"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dbt-duckdb>=1.8,<2.0",
]

