MODEL (
  name omop.cdm_source,
  kind FULL,
  columns (
    cdm_source_name TEXT,
    cdm_source_abbreviation TEXT,
    cdm_holder TEXT,
    source_description TEXT,
    source_documentation_reference TEXT,
    cdm_etl_reference TEXT,
    source_release_date DATE,
    cdm_release_date DATE,
    cdm_version TEXT,
    vocabulary_version TEXT,
    cdm_version_concept_id INT
  )
);

SELECT
  'Synthea SQLMesh Tutorial CDM' AS cdm_source_name,
  'SYNTHEA-SQLMESH' AS cdm_source_abbreviation,
  'OHDSI' AS cdm_holder,
  'Synthetic patient data generated by Synthea and transformed via SQLMesh tutorial ETL.' AS source_description,
  'https://synthetichealth.github.io/synthea/' AS source_documentation_reference,
  'https://github.com/OHDSI/ETL-Synthea' AS cdm_etl_reference,
  CURRENT_DATE AS source_release_date,
  CURRENT_DATE AS cdm_release_date,
  'OMOP CDM v5.4' AS cdm_version,
  'Tutorial subset vocabulary' AS vocabulary_version,
  756265 AS cdm_version_concept_id;
