MODEL (
  name omop.dose_era,
  kind FULL,
  description "A Dose Era is defined as a span of time when the Person is assumed to be exposed to a constant dose of a specific active ingredient.",
  columns (
    dose_era_id BIGINT,
    person_id BIGINT,
    drug_concept_id INT,
    unit_concept_id INT,
    dose_value REAL,
    dose_era_start_date DATE,
    dose_era_end_date DATE
  ),
  depends_on (
    vocab.concept,
    omop.person,
  ),
  audits (
    person_completeness_dose_era,
    dose_era_dose_era_end_date_is_required,
    dose_era_dose_era_end_date_after_birth,
    dose_era_dose_era_id_is_required,
    dose_era_dose_era_id_is_primary_key,
    dose_era_dose_era_start_date_is_required,
    dose_era_dose_era_start_date_start_before_end,
    dose_era_dose_era_start_date_after_birth,
    dose_era_dose_value_is_required,
    dose_era_drug_concept_id_is_required,
    dose_era_drug_concept_id_is_foreign_key,
    dose_era_drug_concept_id_fk_domain,
    dose_era_drug_concept_id_is_standard_valid_concept,
    dose_era_drug_concept_id_standard_concept_record_completeness,
    dose_era_person_id_is_required,
    dose_era_person_id_is_foreign_key,
    dose_era_unit_concept_id_is_required,
    dose_era_unit_concept_id_is_foreign_key,
    dose_era_unit_concept_id_fk_domain,
    dose_era_unit_concept_id_is_standard_valid_concept,
    dose_era_unit_concept_id_standard_concept_record_completeness
  )
);

/* Note: This model is typically generated by OMOP-specific tools or derived datasets, */ /* not directly from raw Synthea data in this basic ETL. */ /* Creating an empty table structure for compatibility. */
SELECT
  NULL::BIGINT AS dose_era_id,
  NULL::BIGINT AS person_id,
  NULL::INT AS drug_concept_id,
  NULL::INT AS unit_concept_id,
  NULL::REAL AS dose_value,
  NULL::DATE AS dose_era_start_date,
  NULL::DATE AS dose_era_end_date
WHERE
  1 = 0