MODEL (
  name omop.fact_relationship,
  kind FULL,
  description "The FACT_RELATIONSHIP table contains records about the relationships between facts stored as records in any table of the CDM.",
  columns (
    domain_concept_id_1 INT,
    fact_id_1 BIGINT,
    domain_concept_id_2 INT,
    fact_id_2 BIGINT,
    relationship_concept_id INT
  ),
  depends_on (
    vocab.concept,
  ),
  audits (
    fact_relationship_domain_concept_id_1_is_required,
    fact_relationship_domain_concept_id_1_is_foreign_key,
    fact_relationship_domain_concept_id_1_standard_concept_record_completeness,
    fact_relationship_domain_concept_id_2_is_required,
    fact_relationship_domain_concept_id_2_is_foreign_key,
    fact_relationship_domain_concept_id_2_standard_concept_record_completeness,
    fact_relationship_fact_id_1_is_required,
    fact_relationship_fact_id_2_is_required,
    fact_relationship_relationship_concept_id_is_required,
    fact_relationship_relationship_concept_id_is_foreign_key,
    fact_relationship_relationship_concept_id_standard_concept_record_completeness
  )
);

/* Note: This model is typically generated by OMOP-specific tools or derived datasets, */ /* not directly from raw Synthea data in this basic ETL. */ /* Creating an empty table structure for compatibility. */
SELECT
  NULL::INT AS domain_concept_id_1,
  NULL::BIGINT AS fact_id_1,
  NULL::INT AS domain_concept_id_2,
  NULL::BIGINT AS fact_id_2,
  NULL::INT AS relationship_concept_id
WHERE
  1 = 0