MODEL (
  name omop.note,
  description 'The NOTE table captures unstructured information that was recorded by a provider about a patient in free text notes.',
  kind FULL,
  columns (
    note_id BIGINT,
    person_id BIGINT,
    note_date DATE,
    note_datetime TIMESTAMP,
    note_type_concept_id INT,
    note_class_concept_id INT,
    note_title TEXT,
    note_text TEXT,
    encoding_concept_id INT,
    language_concept_id INT,
    provider_id BIGINT,
    visit_occurrence_id BIGINT,
    visit_detail_id BIGINT,
    note_source_value TEXT,
    note_event_id BIGINT,
    note_event_field_concept_id INT
  ),
  depends_on (
    vocab.concept,
    omop.person,
    omop.provider,
    omop.visit_detail,
    omop.visit_occurrence,
  ),
  audits (
    person_completeness_note,
    note_encoding_concept_id_is_required,
    note_encoding_concept_id_is_foreign_key,
    note_encoding_concept_id_is_standard_valid_concept,
    note_language_concept_id_is_required,
    note_language_concept_id_is_foreign_key,
    note_language_concept_id_is_standard_valid_concept,
    note_note_class_concept_id_is_required,
    note_note_class_concept_id_is_foreign_key,
    note_note_class_concept_id_is_standard_valid_concept,
    note_note_date_is_required,
    note_note_date_after_birth,
    note_note_datetime_after_birth,
    note_note_event_field_concept_id_is_foreign_key,
    note_note_event_field_concept_id_is_standard_valid_concept,
    note_note_id_is_required,
    note_note_id_is_primary_key,
    note_note_text_is_required,
    note_note_type_concept_id_is_required,
    note_note_type_concept_id_is_foreign_key,
    note_note_type_concept_id_fk_domain,
    note_note_type_concept_id_is_standard_valid_concept,
    note_person_id_is_required,
    note_person_id_is_foreign_key,
    note_provider_id_is_foreign_key,
    note_visit_detail_id_is_foreign_key,
    note_visit_occurrence_id_is_foreign_key
  )
);

SELECT
  NULL::BIGINT AS note_id,
  NULL::BIGINT AS person_id,
  NULL::DATE AS note_date,
  NULL::TIMESTAMP AS note_datetime,
  NULL::INT AS note_type_concept_id,
  NULL::INT AS note_class_concept_id,
  NULL::TEXT AS note_title,
  NULL::TEXT AS note_text,
  NULL::INT AS encoding_concept_id,
  NULL::INT AS language_concept_id,
  NULL::BIGINT AS provider_id,
  NULL::BIGINT AS visit_occurrence_id,
  NULL::BIGINT AS visit_detail_id,
  NULL::TEXT AS note_source_value,
  NULL::BIGINT AS note_event_id,
  NULL::INT AS note_event_field_concept_id
WHERE
  1 = 0