remote_theme: pmarsceill/just-the-docs
# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  "Synthea OMOP ETL":
    - "//github.com/OHDSI/ETL-Synthea"

# Color scheme currently only supports "dark" or nil (default)
color_scheme: nil
