{{ config(materialized='table', alias='cdm_source') }}

select
    'Synthea SQLMesh Tutorial CDM' as cdm_source_name,
    'SYNTHEA-SQLMESH' as cdm_source_abbreviation,
    'OHDSI' as cdm_holder,
    'Synthetic patient data generated by Synthea and transformed via dbt demo.' as source_description,
    'https://synthetichealth.github.io/synthea/' as source_documentation_reference,
    'https://github.com/OHDSI/ETL-Synthea' as cdm_etl_reference,
    current_date as source_release_date,
    current_date as cdm_release_date,
    'OMOP CDM v5.4' as cdm_version,
    'Tutorial subset vocabulary' as vocabulary_version,
    756265 as cdm_version_concept_id
